site_name: "IHC - Moovit (Grupo 7)"
site_url: https://github.com/th-org/24.2-moovit-ihc
theme:
  name: "material"
  font:
    text: Open Sans
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
  palette:
    - scheme: default  # Modo claro
      primary: 'dark blue'
      accent: 'light blue'
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate  # Modo escuro
      primary: 'blue grey'
      accent: 'cyan'
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: high-contrast  # Modo de alto contraste
      primary: 'black'
      accent: 'yellow'
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast  

nav:
  - Home: index.md
  - Heurísticas de Nielsen: heuristica.md
  - Cronograma: cronograma.md
  - Territórios:
    - Geral: geral_territorio.md
    - Territórios:
      - Território 1: territorios/territorio1.md
      - Território 2: territorios/territorio2.md
      - Território 3: territorios/territorio3.md
      - Território 4: territorios/territorio4.md
      - Território 5: territorios/territorio5.md
      - Território 6: territorios/territorio6.md
      - Território 7: territorios/territorio7.md
      - Território 8: territorios/territorio8.md
  - Formulário de Avaliação: forms.md
  - Métodos Estatísticos: estatistica.md
  - Prototipação no Figma: 
      - Design System: prototipacao/design_system.md
